// renderers/lit/src/v0_9/catalogs/basic/components/AudioPlayer.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, nothing, css} from 'lit';
import {customElement} from 'lit/decorators.js';
import {AudioPlayerApi} from '@a2ui/web_core/v0_9/basic_catalog';
import {BasicCatalogA2uiLitElement} from '../basic-catalog-a2ui-lit-element.js';
import {A2uiController} from '../../../a2ui-controller.js';

@customElement('a2ui-audioplayer')
export class A2uiAudioPlayerElement extends BasicCatalogA2uiLitElement<typeof AudioPlayerApi> {
  static override styles = css`
    :host {
      display: flex;
      flex-direction: column;
      gap: var(--a2ui-spacing-xs, 0.25rem);
      background: var(--a2ui-audioplayer-background, transparent);
      border-radius: var(--a2ui-audioplayer-border-radius, 0);
      padding: var(--a2ui-audioplayer-padding, 0);
    }
  `;

  protected createController() {
    return new A2uiController(this, AudioPlayerApi);
  }

  override render() {
    const props = this.controller.props;
    if (!props) return nothing;

    return html`
      ${props.description ? html`<p>${props.description}</p>` : nothing}
      <audio src=${props.url} controls></audio>
    `;
  }
}

export const A2uiAudioPlayer = {
  ...AudioPlayerApi,
  tagName: 'a2ui-audioplayer',
};

// renderers/react/src/v0_8/components/content/AudioPlayer.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {memo} from 'react';
import type * as Types from '@a2ui/web_core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject} from '../../lib/utils';

/**
 * AudioPlayer component - renders an audio player with optional description.
 */
export const AudioPlayer = memo(function AudioPlayer({
  node,
  surfaceId,
}: A2UIComponentProps<Types.AudioPlayerNode>) {
  const {theme, resolveString} = useA2UIComponent(node, surfaceId);
  const props = node.properties;

  const url = resolveString(props.url);
  const description = resolveString(props.description ?? null);

  if (!url) {
    return null;
  }

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  return (
    <div className="a2ui-audio" style={hostStyle}>
      <section
        className={classMapToString(theme.components.AudioPlayer)}
        style={stylesToObject(theme.additionalStyles?.AudioPlayer)}
      >
        {description && <p>{description}</p>}
        <audio src={url} controls />
      </section>
    </div>
  );
});

export default AudioPlayer;
