// samples/community/client/lit/personalized_learning/src/a2ui-renderer.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * A2UI Renderer
 *
 * Renders A2UI JSON payloads into the chat interface using the A2UI web components.
 * Uses the signal-based model processor for proper reactivity.
 */

import {v0_8} from '@a2ui/lit';
import type {SourceInfo} from './a2a-client';
// Import the theme provider to register the custom element
import './theme-provider.js';

// Type alias for the processor - use the actual exported class name
type A2UIModelProcessorInstance = InstanceType<typeof v0_8.Data.A2uiMessageProcessor>;

// Extended element type for the theme provider wrapper
interface A2UIThemeProviderElement extends HTMLElement {
  surfaceId: string;
  surface: v0_8.Types.Surface;
  processor: A2UIModelProcessorInstance;
}

export class A2UIRenderer {
  private processors: Map<string, A2UIModelProcessorInstance> = new Map();

  /**
   * Render A2UI JSON into a message element.
   */
  render(messageElement: HTMLDivElement, a2uiMessages: unknown[], source?: SourceInfo): void {
    if (!a2uiMessages || a2uiMessages.length === 0) {
      return;
    }

    // Create a container for the A2UI content
    const container = document.createElement('div');
    container.className = 'a2ui-container';

    // Find the message content element
    const contentEl = messageElement.querySelector('.message-content');
    if (!contentEl) {
      console.error('[A2UIRenderer] Message content element not found');
      return;
    }

    contentEl.appendChild(container);

    // Create a model processor for this render
    const processor = v0_8.Data.createSignalA2uiMessageProcessor();

    // Process all A2UI messages to build the model
    try {
      processor.processMessages(a2uiMessages as v0_8.Types.ServerToClientMessage[]);
    } catch (error) {
      console.error('[A2UIRenderer] Error processing messages:', error);
    }

    // Render the surfaces
    const surfaces = processor.getSurfaces();
    for (const [surfaceId, surface] of surfaces.entries()) {
      this.renderSurface(container, surfaceId, surface, processor);
      this.processors.set(surfaceId, processor);
    }

    // Add source attribution if available
    if (source && (source.url || source.provider)) {
      this.renderSourceAttribution(container, source);
    }
  }

  /**
   * Render source attribution below the A2UI content.
   */
  private renderSourceAttribution(container: HTMLElement, source: SourceInfo): void {
    const attribution = document.createElement('div');
    attribution.className = 'source-attribution';

    // If we have a URL, make it a link; otherwise just show the text
    if (source.url) {
      attribution.innerHTML = `
        <span class="source-label">Source:</span>
        <a href="${source.url}" target="_blank" rel="noopener noreferrer" class="source-link">
          ${source.title || source.provider}
        </a>
        <span class="source-provider">— ${source.provider}</span>
      `;
    } else {
      attribution.innerHTML = `
        <span class="source-label">Source:</span>
        <span class="source-link">${source.title || source.provider}</span>
        <span class="source-provider">— ${source.provider}</span>
      `;
    }
    container.appendChild(attribution);
  }

  /**
   * Render a surface using the theme provider wrapper.
   * The theme provider supplies the theme context required by A2UI components.
   */
  private renderSurface(
    container: HTMLElement,
    surfaceId: string,
    surface: v0_8.Types.Surface,
    processor: A2UIModelProcessorInstance,
  ): void {
    // Create the theme provider wrapper which contains the a2ui-surface
    const providerEl = document.createElement('a2ui-theme-provider') as A2UIThemeProviderElement;

    providerEl.surfaceId = surfaceId;
    providerEl.surface = surface;
    providerEl.processor = processor;

    // Add some styling for the container
    providerEl.style.display = 'block';
    providerEl.style.marginTop = '16px';

    container.appendChild(providerEl);
  }

  /**
   * Get a processor for a surface ID.
   */
  getProcessor(surfaceId: string): A2UIModelProcessorInstance | undefined {
    return this.processors.get(surfaceId);
  }

  /**
   * Clear all rendered surfaces.
   */
  clear(): void {
    this.processors.clear();
  }
}

// renderers/react/src/v0_8/core/A2UIRenderer.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Suspense, useMemo, memo, type ReactNode} from 'react';
import {useA2UI} from '../hooks/useA2UI';
import {ComponentNode} from './ComponentNode';
import {type ComponentRegistry} from '../registry/ComponentRegistry';
import {cn} from '../lib/utils';

/** Default loading fallback - memoized to prevent recreation */
const DefaultLoadingFallback = memo(function DefaultLoadingFallback() {
  return (
    <div className="a2ui-loading" style={{padding: '16px', opacity: 0.5}}>
      Loading...
    </div>
  );
});

export interface A2UIRendererProps {
  /** The surface ID to render */
  surfaceId: string;
  /** Additional CSS classes for the surface container */
  className?: string;
  /** Fallback content when surface is not yet available */
  fallback?: ReactNode;
  /** Loading fallback for lazy-loaded components */
  loadingFallback?: ReactNode;
  /** Optional custom component registry */
  registry?: ComponentRegistry;
}

/**
 * A2UIRenderer - renders an A2UI surface.
 *
 * This is the main entry point for rendering A2UI content in your React app.
 * It reads the surface state from the A2UI store and renders the component tree.
 *
 * Memoized to prevent unnecessary re-renders when props haven't changed.
 *
 * @example
 * ```tsx
 * function App() {
 *   return (
 *     <A2UIProvider onAction={handleAction}>
 *       <A2UIRenderer surfaceId="main" />
 *     </A2UIProvider>
 *   );
 * }
 * ```
 */
export const A2UIRenderer = memo(function A2UIRenderer({
  surfaceId,
  className,
  fallback = null,
  loadingFallback,
  registry,
}: A2UIRendererProps) {
  const {getSurface, version} = useA2UI();

  // Get surface - this will re-render when version changes
  const surface = getSurface(surfaceId);

  // Memoize surface styles to prevent object recreation
  // Matches Lit renderer's transformation logic in surface.ts
  const surfaceStyles = useMemo<React.CSSProperties>(() => {
    if (!surface?.styles) return {};

    const styles: React.CSSProperties & Record<string, string> = {};

    for (const [key, value] of Object.entries(surface.styles)) {
      switch (key) {
        // Generate a color palette from the primary color.
        // Values range from 0-100 where 0=black, 100=white, 50=primary color.
        // Uses color-mix to create intermediate values.
        case 'primaryColor': {
          styles['--p-100'] = '#ffffff';
          styles['--p-99'] = `color-mix(in srgb, ${value} 2%, white 98%)`;
          styles['--p-98'] = `color-mix(in srgb, ${value} 4%, white 96%)`;
          styles['--p-95'] = `color-mix(in srgb, ${value} 10%, white 90%)`;
          styles['--p-90'] = `color-mix(in srgb, ${value} 20%, white 80%)`;
          styles['--p-80'] = `color-mix(in srgb, ${value} 40%, white 60%)`;
          styles['--p-70'] = `color-mix(in srgb, ${value} 60%, white 40%)`;
          styles['--p-60'] = `color-mix(in srgb, ${value} 80%, white 20%)`;
          styles['--p-50'] = String(value);
          styles['--p-40'] = `color-mix(in srgb, ${value} 80%, black 20%)`;
          styles['--p-35'] = `color-mix(in srgb, ${value} 70%, black 30%)`;
          styles['--p-30'] = `color-mix(in srgb, ${value} 60%, black 40%)`;
          styles['--p-25'] = `color-mix(in srgb, ${value} 50%, black 50%)`;
          styles['--p-20'] = `color-mix(in srgb, ${value} 40%, black 60%)`;
          styles['--p-15'] = `color-mix(in srgb, ${value} 30%, black 70%)`;
          styles['--p-10'] = `color-mix(in srgb, ${value} 20%, black 80%)`;
          styles['--p-5'] = `color-mix(in srgb, ${value} 10%, black 90%)`;
          styles['--p-0'] = '#000000';
          break;
        }

        case 'font': {
          styles['--font-family'] = String(value);
          styles['--font-family-flex'] = String(value);
          break;
        }
      }
    }
    return styles;
  }, [surface?.styles]);

  // No surface yet
  if (!surface || !surface.componentTree) {
    return <>{fallback}</>;
  }

  // Use provided fallback or default memoized component
  const actualLoadingFallback = loadingFallback ?? <DefaultLoadingFallback />;

  return (
    <div
      className={cn('a2ui-surface', className)}
      style={surfaceStyles}
      data-surface-id={surfaceId}
      data-version={version}
    >
      <Suspense fallback={actualLoadingFallback}>
        <ComponentNode node={surface.componentTree} surfaceId={surfaceId} registry={registry} />
      </Suspense>
    </div>
  );
});

export default A2UIRenderer;
