// renderers/lit/src/0.8/ui/checkbox.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, css, nothing} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import {Root} from './root.js';
import * as Primitives from '@a2ui/web_core/types/primitives';
import {A2uiMessageProcessor} from '@a2ui/web_core/data/model-processor';
import {classMap} from 'lit/directives/class-map.js';
import {styleMap} from 'lit/directives/style-map.js';
import {structuralStyles} from './styles.js';
import {extractStringValue} from './utils/utils.js';

@customElement('a2ui-checkbox')
export class Checkbox extends Root {
  @property()
  accessor value: Primitives.BooleanValue | null = null;

  @property()
  accessor label: Primitives.StringValue | null = null;

  static styles = [
    structuralStyles,
    css`
      * {
        box-sizing: border-box;
      }

      :host {
        display: block;
        flex: var(--weight);
        min-height: 0;
        overflow: auto;
      }

      input {
        display: block;
        width: 100%;
      }

      .description {
        font-size: 14px;
        margin-bottom: 4px;
      }
    `,
  ];

  #setBoundValue(value: boolean) {
    if (!this.value || !this.processor) {
      return;
    }

    if (!('path' in this.value)) {
      return;
    }

    if (!this.value.path) {
      return;
    }

    this.processor.setData(
      this.component,
      this.value.path,
      value,
      this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID,
    );
  }

  #renderField(value: boolean | number) {
    return html` <section
      class=${classMap(this.theme.components.CheckBox.container)}
      style=${this.theme.additionalStyles?.CheckBox
        ? styleMap(this.theme.additionalStyles?.CheckBox)
        : nothing}
    >
      <input
        class=${classMap(this.theme.components.CheckBox.element)}
        autocomplete="off"
        @input=${(evt: Event) => {
          if (!(evt.target instanceof HTMLInputElement)) {
            return;
          }

          this.#setBoundValue(evt.target.checked);
        }}
        id="data"
        type="checkbox"
        .checked=${value}
      />
      <label class=${classMap(this.theme.components.CheckBox.label)} for="data"
        >${extractStringValue(this.label, this.component, this.processor, this.surfaceId)}</label
      >
    </section>`;
  }

  render() {
    if (this.value && typeof this.value === 'object') {
      if ('literalBoolean' in this.value && this.value.literalBoolean) {
        return this.#renderField(this.value.literalBoolean);
      } else if ('literal' in this.value && this.value.literal !== undefined) {
        return this.#renderField(this.value.literal);
      } else if (this.value && 'path' in this.value && this.value.path) {
        if (!this.processor || !this.component) {
          return html`(no model)`;
        }

        const textValue = this.processor.getData(
          this.component,
          this.value.path,
          this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID,
        );

        if (textValue === null) {
          return html`Invalid label`;
        }

        if (typeof textValue !== 'boolean') {
          return html`Invalid label`;
        }

        return this.#renderField(textValue);
      }
    }

    return nothing;
  }
}

// renderers/react/src/v0_8/components/interactive/CheckBox.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState, useCallback, useEffect, useId, memo} from 'react';
import type * as Types from '@a2ui/web_core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject} from '../../lib/utils';

/**
 * CheckBox component - a boolean toggle with a label.
 *
 * Supports two-way data binding for the checked state.
 */
export const CheckBox = memo(function CheckBox({
  node,
  surfaceId,
}: A2UIComponentProps<Types.CheckboxNode>) {
  const {theme, resolveString, resolveBoolean, setValue, getValue} = useA2UIComponent(
    node,
    surfaceId,
  );
  const props = node.properties;
  const id = useId();

  const label = resolveString(props.label);
  const valuePath = props.value?.path;
  const initialChecked = resolveBoolean(props.value) ?? false;

  const [checked, setChecked] = useState(initialChecked);

  // Sync with external data model changes (path binding)
  useEffect(() => {
    if (valuePath) {
      const externalValue = getValue(valuePath);
      if (externalValue !== null && Boolean(externalValue) !== checked) {
        setChecked(Boolean(externalValue));
      }
    }
  }, [valuePath, getValue]); // eslint-disable-line react-hooks/exhaustive-deps

  // Sync when literal value changes from props (server-driven updates via surfaceUpdate)
  useEffect(() => {
    if (props.value?.literalBoolean !== undefined) {
      setChecked(props.value.literalBoolean);
    }
  }, [props.value?.literalBoolean]);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const newValue = e.target.checked;
      setChecked(newValue);

      // Two-way binding: update data model
      if (valuePath) {
        setValue(valuePath, newValue);
      }
    },
    [valuePath, setValue],
  );

  // Structure mirrors Lit's CheckBox component:
  //   <div class="a2ui-checkbox">  ← :host equivalent
  //     <section class="...">      ← internal element
  //       <input>...</input>
  //       <label>...</label>
  //     </section>
  //   </div>

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  return (
    <div className="a2ui-checkbox" style={hostStyle}>
      <section
        className={classMapToString(theme.components.CheckBox.container)}
        style={stylesToObject(theme.additionalStyles?.CheckBox)}
      >
        <input
          type="checkbox"
          id={id}
          checked={checked}
          onChange={handleChange}
          className={classMapToString(theme.components.CheckBox.element)}
        />
        {label && (
          <label htmlFor={id} className={classMapToString(theme.components.CheckBox.label)}>
            {label}
          </label>
        )}
      </section>
    </div>
  );
});

export default CheckBox;
