// renderers/angular/src/v0_8/components/datetime-input.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {ChangeDetectionStrategy, Component, computed, input} from '@angular/core';
import {DynamicComponent} from '../rendering/dynamic-component';
import type {DateTimeInputNode, StringValue} from '../types';

@Component({
  selector: 'a2ui-datetime-input',
  template: `
    <div
      [class]="theme.components.DateTimeInput.container"
      [style]="theme.additionalStyles?.DateTimeInput"
    >
      <label [class]="theme.components.DateTimeInput.label" [for]="inputId">
        {{ resolvedLabel() }}
      </label>
      <input
        [type]="inputType()"
        [class]="theme.components.DateTimeInput.element"
        [id]="inputId"
        [value]="resolvedValue() ?? ''"
        (change)="onChange($event)"
      />
    </div>
  `,
  styles: `
    :host {
      display: block;
    }
    input,
    input::-webkit-datetime-edit,
    input::-webkit-datetime-edit-fields-wrapper {
      color: #333;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DateTimeInput extends DynamicComponent<DateTimeInputNode> {
  readonly label = input<StringValue | null>(null);
  readonly value = input.required<StringValue | null>();
  readonly enableDate = input<boolean>(true);
  readonly enableTime = input<boolean>(false);

  protected readonly inputId = super.getUniqueId('a2ui-datetime-input');

  protected inputType = computed(() => {
    if (this.enableDate() && this.enableTime()) return 'datetime-local';
    if (this.enableTime()) return 'time';
    return 'date';
  });

  protected readonly resolvedLabel = computed(() => super.resolvePrimitive(this.label()));
  protected resolvedValue = computed(() => super.resolvePrimitive(this.value()));

  onChange(event: Event) {
    const value = (event.target as HTMLInputElement).value;
    const valueNode = this.value();
    if (valueNode && typeof valueNode === 'object' && 'path' in valueNode && valueNode.path) {
      // Update the local data model directly to ensure immediate UI feedback and avoid unnecessary network requests.
      this.processor.processMessages([
        {
          dataModelUpdate: {
            surfaceId: this.surfaceId()!,
            path: this.processor.resolvePath(
              valueNode.path as string,
              this.component().dataContextPath,
            ),
            contents: [{key: '.', valueString: value}],
          },
        },
      ]);
    } else {
      this.handleAction('change', {value});
    }
  }

  private handleAction(name: string, context: Record<string, unknown>) {
    super.sendAction({
      name,
      context: Object.entries(context).map(([key, val]) => ({
        key,
        value: typeof val === 'number' ? {literalNumber: val} : {literalString: String(val)},
      })),
    });
  }
}

// renderers/react/src/v0_8/components/interactive/DateTimeInput.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState, useCallback, useEffect, useId, memo} from 'react';
import type * as Types from '@a2ui/web_core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject} from '../../lib/utils';

/**
 * DateTimeInput component - a date and/or time picker.
 *
 * Supports enabling date, time, or both. Uses native HTML5 date/time inputs.
 */
export const DateTimeInput = memo(function DateTimeInput({
  node,
  surfaceId,
}: A2UIComponentProps<Types.DateTimeInputNode>) {
  const {theme, resolveString, setValue, getValue} = useA2UIComponent(node, surfaceId);
  const props = node.properties;
  const id = useId();

  const valuePath = props.value?.path;
  const initialValue = resolveString(props.value) ?? '';
  const enableDate = props.enableDate ?? true;
  const enableTime = props.enableTime ?? false;

  const [value, setLocalValue] = useState(initialValue);

  // Sync with external data model changes
  useEffect(() => {
    if (valuePath) {
      const externalValue = getValue(valuePath);
      if (externalValue !== null && String(externalValue) !== value) {
        setLocalValue(String(externalValue));
      }
    }
  }, [valuePath, getValue]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const newValue = e.target.value;
      setLocalValue(newValue);

      // Two-way binding: update data model
      if (valuePath) {
        setValue(valuePath, newValue);
      }
    },
    [valuePath, setValue],
  );

  // Determine input type based on enableDate and enableTime
  let inputType: 'date' | 'time' | 'datetime-local' = 'date';
  if (enableDate && enableTime) {
    inputType = 'datetime-local';
  } else if (enableTime && !enableDate) {
    inputType = 'time';
  }

  // Get placeholder text to match Lit renderer
  const getPlaceholderText = () => {
    if (enableDate && enableTime) {
      return 'Date & Time';
    } else if (enableTime) {
      return 'Time';
    }
    return 'Date';
  };

  // Structure mirrors Lit's DateTimeInput component:
  //   <div class="a2ui-datetime-input">  ← :host equivalent
  //     <section class="...">            ← container theme classes
  //       <label>                        ← label
  //       <input>                        ← input element
  //     </section>
  //   </div>

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  return (
    <div className="a2ui-datetime-input" style={hostStyle}>
      <section className={classMapToString(theme.components.DateTimeInput.container)}>
        <label htmlFor={id} className={classMapToString(theme.components.DateTimeInput.label)}>
          {getPlaceholderText()}
        </label>
        <input
          type={inputType}
          id={id}
          value={value}
          onChange={handleChange}
          className={classMapToString(theme.components.DateTimeInput.element)}
          style={stylesToObject(theme.additionalStyles?.DateTimeInput)}
        />
      </section>
    </div>
  );
});

export default DateTimeInput;
