// renderers/react/src/v0_8/components/interactive/Button.tsx
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useCallback, memo} from 'react';
import type * as Types from '@a2ui/web_core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject} from '../../lib/utils';
import {ComponentNode} from '../../core/ComponentNode';

/**
 * Button component - a clickable element that triggers an action.
 *
 * Contains a child component (usually Text or Icon) and dispatches
 * a user action when clicked.
 */
export const Button = memo(function Button({
  node,
  surfaceId,
}: A2UIComponentProps<Types.ButtonNode>) {
  const {theme, sendAction} = useA2UIComponent(node, surfaceId);
  const props = node.properties;

  const handleClick = useCallback(() => {
    if (props.action) {
      sendAction(props.action);
    }
  }, [props.action, sendAction]);

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  return (
    <div className="a2ui-button" style={hostStyle}>
      <button
        className={classMapToString(theme.components.Button)}
        style={stylesToObject(theme.additionalStyles?.Button)}
        onClick={handleClick}
      >
        <ComponentNode node={props.child} surfaceId={surfaceId} />
      </button>
    </div>
  );
});

export default Button;

// renderers/angular/src/v0_8/components/button.ts
/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {ChangeDetectionStrategy, Component, input} from '@angular/core';
import type {ButtonNode, Action, AnyComponentNode} from '../types';
import {DynamicComponent} from '../rendering/dynamic-component';
import {Renderer} from '../rendering/renderer';

@Component({
  selector: 'a2ui-button',
  imports: [Renderer],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      [class]="theme.components.Button"
      [style]="theme.additionalStyles?.Button"
      (click)="handleClick()"
    >
      @if (child()) {
        <ng-container
          a2ui-renderer
          [surfaceId]="surfaceId()!"
          [component]="child() ?? component().properties.child"
        />
      }
    </button>
  `,
  styles: `
    :host {
      display: block;
      flex: var(--weight);
      min-height: 0;
    }
  `,
})
export class Button extends DynamicComponent<ButtonNode> {
  readonly action = input<Action | null>(null);
  readonly child = input<AnyComponentNode | null>(null);
  // This is currently not handled by the template.
  readonly primary = input<boolean | null>(false);

  protected handleClick() {
    const action = this.action();

    if (action) {
      super.sendAction(action);
    }
  }
}
